

all: 
	(cd unittest/testcode; make)
# (cd unittest/mdhwcet; make)
	make -f local.mk

clean:
	(cd unittest/testcode; make clean)
# (cd unittest/mdhwcet; make clean)
	make -f local.mk clean

test:
	(cd unittest/testcode; make)
# (cd unittest/mdhwcet; make)
	make -f local.mk test


